# ??? ??????????
spring.application.name=smart_gate

# ????????? ??????????? ? SQLite
# ???? smart_gate.db ????? ?????? ? ???????? ????? ???????
spring.datasource.url=jdbc:sqlite:smart_gate.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# ??????? ??? Hibernate, ????? ?? ??????? ????????? SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# ?????????????? ???????? ?????? ?? ?????? Java-??????? (Entity)
# 'update' ????????, ??? Spring ????? ????????? ????????? ?? ??? ?????????? ? ????
spring.jpa.hibernate.ddl-auto=update

# ???????? ??????????? SQL-???????? ? ??????? (??????? ??????, ??? ????? ? ????)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true